# Generated by Django 3.1.2 on 2020-12-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201205_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('msg', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='product_des',
            name='product_desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
