# Generated by Django 3.1.2 on 2020-12-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201212_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemjson', models.CharField(max_length=1000)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('country', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zipcode', models.IntegerField(default=0)),
            ],
        ),
    ]
