# Generated by Django 3.1.2 on 2020-12-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totall',
            field=models.CharField(default='', max_length=150),
        ),
    ]
